# Generated by Django 2.2 on 2021-10-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20211012_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
